// import SmoothScroll from '@/components/LenisLayout';
import { Roboto, Source_Sans_3 } from 'next/font/google';
import { getServerSession } from 'next-auth';
import SessionProvider from './components/SessionProvider';
import Nav from './components/Nav';
import Footer from './components/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import './globals.css';

import GalleryModal from '@/app/components/GalleryModal';

// const inter = Inter({ subsets: ["latin"] });
// const madimiOne = MadimiOne({
//   subsets: ['latin'],
// });
const roboto = Roboto({
  subsets: ['latin'],
  weight: '500',
});

const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
            <Head>
        <link
          rel="preload"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/fonts/bootstrap-icons.woff2?48804dbfe98a9c8a08858a0de0b0e3db"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={sourceSans3.className}>
        <SessionProvider session={session}>
          <Nav />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
