import { Inter } from "next/font/google";
import { MadimiOne } from 'next/font/google';
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const madimiOne = MadimiOne({
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={madimiOne.className}>{children}</body>
    </html>
  );
}
